spring:
    datasource:
        password: root
        url: jdbc:postgresql://localhost/task_db
        username: root

        driver-class-name=org:
            postgresql:
                Driver:jpa:
        generate-ddl: true
        database: postgresql
        database-platform: "org.hibernate.dialect.PostgreSQLxxDialect"
#logging:
#    level: info
